(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib._970x250 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// rainbow
	this.instance = new lib.mc_rainbow();
	this.instance.setTransform(6,125,0.394,0.282,90,0,0,317.3,21.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(425));

	// boton
	this.instance_1 = new lib.mc_boton();
	this.instance_1.setTransform(737.4,152.5,0.145,0.145);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(289).to({_off:false},0).to({scaleX:1.34,scaleY:1.34},11).to({scaleX:1.18,scaleY:1.18},3).wait(16).to({scaleX:1.42,scaleY:1.42},3).to({scaleX:1.18,scaleY:1.18},3).wait(19).to({scaleX:1.42,scaleY:1.42},3).to({scaleX:1.18,scaleY:1.18},3).wait(20).to({scaleX:1.42,scaleY:1.42},3).to({scaleX:1.18,scaleY:1.18},3).wait(49));

	// ypide
	this.instance_2 = new lib.mc_ypide();
	this.instance_2.setTransform(368.6,158.4,1.669,1.669);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(265).to({_off:false},0).to({y:147.2,alpha:1},15).wait(145));

	// ingresa
	this.instance_3 = new lib.mc_ingresa();
	this.instance_3.setTransform(692.4,101.3,1.669,1.669);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(250).to({_off:false},0).to({y:88.7,alpha:1},15).wait(160));

	// sieres
	this.instance_4 = new lib.mc_sieres();
	this.instance_4.setTransform(265,105.8,1.669,1.669);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(250).to({_off:false},0).to({y:90.6,alpha:1},15).wait(160));

	// logo
	this.instance_5 = new lib.mc_logo();
	this.instance_5.setTransform(-85.8,21.4,1.578,1.578,0,0,0,50,5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(235).to({_off:false},0).to({x:103},9).wait(181));

	// fondo
	this.instance_6 = new lib.mc_fondo();
	this.instance_6.setTransform(168,140);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(224).to({_off:false},0).to({alpha:1},11).wait(190));

	// pantalla
	this.instance_7 = new lib.mc_pantalla();
	this.instance_7.setTransform(291.5,46.4);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(132).to({_off:false},0).to({_off:true},17).wait(15).to({_off:false},0).to({_off:true},18).wait(11).to({_off:false},0).wait(232));

	// prestamo
	this.instance_8 = new lib.mc_prestamo();
	this.instance_8.setTransform(1231,134.2,1.67,1.67);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(110).to({_off:false},0).to({x:698.3},11).to({x:733.3},4).wait(300));

	// espedir
	this.instance_9 = new lib.mc_espedir();
	this.instance_9.setTransform(1285.6,82.3,1.67,1.67);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(99).to({_off:false},0).to({x:743.5},11).to({x:777},4).wait(311));

	// pc
	this.instance_10 = new lib.mc_pc();
	this.instance_10.setTransform(168,140);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(85).to({_off:false},0).to({alpha:1},14).wait(326));

	// comoesto
	this.instance_11 = new lib.mc_comoesto();
	this.instance_11.setTransform(-100.6,86.1,1.367,1.367);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(20).to({_off:false},0).to({x:144.1},11).to({x:134.1},4).wait(390));

	// tanpractico
	this.instance_12 = new lib.mc_tanpractico();
	this.instance_12.setTransform(-140.6,44,1.367,1.367);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({_off:false},0).to({x:186.2},11).to({x:170.5},4).wait(401));

	// polo3
	this.instance_13 = new lib.img_polo3min();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_13}]},56).wait(369));

	// polo2
	this.instance_14 = new lib.img_polo2min();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_14}]},46).wait(379));

	// polo1
	this.instance_15 = new lib.img_polo1min();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_15}]}).wait(425));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


// symbols:
(lib.img_botonmin = function() {
	this.initialize(img.img_botonmin);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,135,44);


(lib.img_fondocremamin = function() {
	this.initialize(img.img_fondocremamin);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.img_pantallamin = function() {
	this.initialize(img.img_pantallamin);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,110,42);


(lib.img_pcmin = function() {
	this.initialize(img.img_pcmin);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.img_polo1min = function() {
	this.initialize(img.img_polo1min);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.img_polo2min = function() {
	this.initialize(img.img_polo2min);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.img_polo3min = function() {
	this.initialize(img.img_polo3min);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.mc_ypide = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A60A5").s().p("ARpByIAAg6QgHAGgJADQgKAEgMAAQgQAAgNgHQgMgHgIgPQgIgOAAgXQAAgZAJgQQAIgQAOgHQANgIARAAQANABAJADQAJAEAIAHQABgGAFgDQAEgDAFAAIATAAIAAC0gARBgkQgHAEgEAJQgFAJAAAOQAAAPACAKQAEAJAGAEQAGAEALAAQAHAAAHgDQAIgCAFgFIAAg/QgEgEgHgCQgGgCgHAAIgCAAQgHAAgHADgA0wBmIAAiBIANAAQADAAABADQACACAAAIQAGgGAIgEQAIgEALAAQAKAAAIAEQAJAFAEALQAGAJAAASQAAATgGALQgGALgJAFQgKAFgLAAQgJAAgHgCQgGgDgGgEIAAApgA0QgJIgNAIIAAAwQAFAFAFACQAGACAIAAQAGAAAGgDQAHgDADgHQAFgIAAgOQgBgOgDgHQgEgHgFgDQgGgDgGAAQgHABgGADgA2tBmIAAgGIAOgfIglhWIAAgGIASAAIAcBEIABAAIAahEIARAAIAAAGIgyB7gAioBAQgLgJAAgWIAAhJIgRAAIAAgaIARAAIAAglIAmAAIAAAlIAcAAIAAAaIgcAAIAABFQAAAKAFADQADAEAKAAIAKAAIAAAXIgKADIgNABIgDAAQgTAAgKgJgAVVA2QgSgTAAghQAAgVAJgQQAJgQAPgJQAPgIATgBQAfAAAQARQAQARAAAjIAAAFIAAAFIhbAAQACAOAEAHQAEAIAIADQAJAEAKgBQAMAAAJgDQAKgDAGgFIAMAAIAAAZQgIAFgNAEQgNAEgVABQgigBgSgSgAWfgLQAAgTgHgHQgGgHgMAAQgGAAgGACQgFADgEAHQgFAIgBANIA0AAIAAAAgATBBFQgIgDgGgIQgFgJAAgOIAAhlIAmAAIAABbQAAALAGAEQAFAEAKAAQAHAAAHgCIAPgFIAAhnIAmAAIAACJIgaAAQgFAAgDgDQgDgCgBgIQgJAHgNAEQgMAEgNAAQgMAAgKgEgAOQBAQgQgIgKgQQgJgQAAgWQAAgVAJgQQAKgQAQgJQAQgIAUgBQATABAQAIQARAJAJAQQAJAQABAVQgBAWgJAQQgJAQgRAIQgQAJgTAAQgUAAgQgJgAOdgeQgIALgBAVQABAXAIAKQAJAKAOAAQAPAAAIgKQAJgKAAgXQAAgVgJgLQgIgLgPAAQgOAAgJALgAE4BAQgQgIgJgQQgKgQAAgWQAAgVAKgQQAJgQAQgJQAQgIAUgBQATABARAIQAQAJAJAQQAKAQAAAVQAAAWgKAQQgJAQgQAIQgRAJgTAAQgUAAgQgJgAFFgeQgIALgBAVQABAXAIAKQAIAKAPAAQAOAAAJgKQAIgKAAgXQAAgVgIgLQgJgLgOAAQgPAAgIALgAm5A2QgSgTAAghQAAgVAJgQQAJgQAPgJQAPgIATgBQAgAAAPARQAQARAAAjIAAAFIAAAFIhbAAQACAOAEAHQAFAIAHADQAJAEAKgBQAMAAAJgDQAJgDAHgFIAMAAIAAAZQgIAFgNAEQgNAEgUABQgjgBgSgSgAlvgLQAAgTgHgHQgGgHgMAAQgGAAgGACQgFADgEAHQgFAIgBANIA0AAIAAAAgAH5BEQgKgFgGgJQgFgKAAgNQAAgPAGgKQAIgHAMgFQANgFAQAAIAOABIAOACIAAgNQgBgKgFgFQgGgEgOAAQgLAAgJADQgJADgHAEIgLAAIAAgbQAKgFANgDQAMgDATgBQAcAAAPALQAOAKAAAYIAABfIgQAAQgJAAgEgDQgFgDgDgIQgHAIgKAEQgKADgMAAQgOAAgKgEgAIQAOQgHAEAAAKQAAAKAGAFQAGAFAKAAQAHAAAGgDQAGgDAFgFIAAgaQgKgCgKAAQgMAAgHAFgAhOBEQgKgFgGgJQgFgKAAgNQAAgPAGgKQAIgHAMgFQANgFAQAAIAOABIAOACIAAgNQgBgKgFgFQgGgEgOAAQgLAAgJADQgJADgHAEIgLAAIAAgbQAKgFANgDQAMgDATgBQAcAAANALQAOAKAAAYIAABfIgQAAQgHAAgEgDQgFgDgDgIQgHAIgKAEQgKADgMAAQgOAAgKgEgAg3AOQgHAEAAAKQAAAKAGAFQAGAFAKAAQAHAAAGgDQAGgDAFgFIAAgaQgKgCgKAAQgMAAgHAFgAklBFQgLgDgJgFIAAgdIAMAAQAGAFAIADQAIAEAMAAQANAAAFgDQAHgEAAgGQAAgGgGgEQgEgDgPgCQgXgCgMgKQgMgIABgUQAAgVAOgMQAOgLAaAAQAPAAALADQAKACAIAFIAAAcIgLAAQgFgEgJgDQgHgCgMgBQgKAAgGAEQgEADAAAGQAAAFAFADQAHADAOACQAQACALAFQAKAFAFAHQAFAIAAAOQAAAVgOAMQgOAMgfAAQgQAAgMgDgAtQBGQgGgDgEgGQgDgFgBgKIAAhJIAUAAIAABEQAAAKAFADQADADAIAAQAHAAAIgDQAHgDAFgEIAAhKIAUAAIAABiIgMAAQgDAAgCgCQgCgCAAgHQgIAFgJAEQgJADgKAAQgIAAgGgCgAuSBCQgHgGAAgOIAAg7IgMAAIAAgOIAMAAIAAgbIATAAIAAAbIAWAAIAAAOIgWAAIAAA5QAAAIAEADQADADAHgBIAJAAIAAANIgHABIgJABQgMAAgHgGgAwaBCQgLgGgFgMQgGgLABgQQAAgQAFgJQAGgMAKgGQALgGANAAQAUAAAKAMQALALAAAXIAAAEIAAADIhCAAQAAARAIAIQAIAHANAAQAKAAAHgCIALgHIAGAAIAAAOIgOAHQgIADgOAAQgQAAgKgGgAvsAMQAAgOgGgHQgFgGgLAAQgKAAgGAHQgHAGgCAOIAvAAIAAAAgAyIBDQgJgFgFgLQgGgLABgSQgBgTAHgJQAGgMAJgFQAJgFAKAAQALAAAGADQAHACAFAFIAAgqIALAAQAFAAACACQABADAAAIIAAB2IgNAAQgDAAgBgDQgBgDgBgIQgFAHgIAEQgIAEgKAAQgKAAgJgFgAx6gKQgGADgEAHQgEAHAAAOQAAAOADAIQADAIAFADQAGAEAGAAQAJgBAGgDQAGgDAGgHIAAgwQgEgEgGgCQgGgDgHAAQgHAAgGADgAMbBHIAAibIgyAAIAAgdICPAAIAAAdIgzAAIAACbgAJ6BHIAAi4IAXAAQAHAAADACQADABACAFIABAOIAACigADZBHIAAhbQAAgKgDgEQgEgEgJABQgIAAgHACIgOAEIAABmIgnAAIAAhbQAAgKgEgEQgDgEgJABQgJAAgHACIgNAEIAABmIgoAAIAAiJIAbAAQAFAAACADQADADACAIQAJgHANgFQANgEAOgBQALAAAIAEQAJAEAFAKQAKgIAOgFQANgEAOgBQAKAAAIAEQAJADAFAJQAEAJAAAOIAABlgAooBHIAAiJIAaAAQAGgBACAEQADADACAKQAGgHAJgFQAKgFANgBIAEABIAFABIAAAeIgHAAQgOAAgLADQgJACgGADIAABjgArEBHIAAi4IA+AAQAjAAATAPQATAOAAAeQAAAegTAPQgUANgjAAIgUAAIAABDgAqbgWIAUAAQASAAAIgIQAGgIAAgPQAAgKgCgHQgDgGgIgEQgHgDgMAAIgUAAgAzDBHIAAhiIALAAIAFABQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIABAJIAABTgAzBgpQgDgDgBgFQABgFADgDQADgDAFAAQAFAAADADQADADAAAFQAAAFgDADQgDADgFAAQgFAAgDgDgAmThMIAAgIIAJgdIAoAAIAAALIgbAag");
	this.shape.setTransform(0,2.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-147.8,-9.1,295.6,22.9);


(lib.mc_tanpractico = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlACeIAAj1IAjAAQAHAAAEADQAEAEABAMQAKgKAPgGQAOgGATAAQATAAAQAJQARAJAKAVQALAUAAAgQAAAjgMAWQgMAVgSAJQgTAKgWAAQgPAAgLgEQgMgDgJgHIAABKgAjogxQgIgBgKADIgSAHIAABbQAHAFAIADQAJACAKAAQAMABAJgFQAKgEAGgMQAGgNAAgXQAAgVgGgMQgFgNgKgEQgIgFgKAAIgCABgAGrBbQgPgNAAgcIAAhlIgXAAIAAgkIAXAAIAAgzIA0AAIAAAzIAmAAIAAAkIgmAAIAABeQAAAOAGAEQAGAGANAAIAOAAIAAAfIgOAEQgIABgLAAIgCAAQgaAAgPgMgANGBbQgWgLgNgVQgNgWAAgfQAAgcANgWQANgWAWgMQAWgMAbAAQAaAAAWAMQAWAMANAWQANAWAAAcQAAAfgNAWQgNAVgWALQgWAMgaAAQgbAAgWgMgAOWAzQALgOABgeQgBgdgLgPQgMgPgTgBQgUABgMAPQgLAPgBAdQABAeALAOQAMAOAUAAQATAAAMgOgAJ+BNQgZgZAAguQAAgdANgWQANgVAWgMQAXgMAdAAQAWAAAOAFQAOADAIAFIAAAnIgUAAQgGgFgKgEQgJgFgNABQgVAAgNAOQgNAPAAAcQAAAeAMAPQANAOAVAAQAQgBAKgFQAKgEAGgFIASAAIAAAkQgJAFgPAGQgQAFgWABQgugBgagZgADsBNQgagZAAguQAAgdANgWQANgVAXgMQAXgMAcAAQAWAAAOAFQAOADAIAFIAAAnIgUAAQgFgFgKgEQgKgFgNABQgUAAgNAOQgNAPgBAcQABAeAMAPQAMAOAVAAQARgBAKgFQAJgEAGgFIASAAIAAAkQgIAFgQAGQgPAFgWABQgvgBgZgZgABOBmQgSAAgOgHQgNgFgIgOQgIgMAAgSQAAgVAJgMQAKgNARgFQARgGAWAAIAUAAIASADIAAgSQAAgNgIgGQgIgHgTAAQgPABgMADQgMAEgKAHIgPAAIAAglQAOgGARgFQARgFAYAAQAnAAAUAOQAUAOAAAhIAACBIgWAAQgMAAgGgEQgHgDgDgMQgKAMgNAEQgNAFgPAAIgDAAgABNAWQgJAHAAANQAAAOAIAGQAIAHANAAQAKAAAIgEQAIgEAHgGIAAgkQgNgDgOAAQgQABgKAFgArmBmQgSAAgNgHQgOgFgIgOQgIgMAAgSQAAgVAKgMQAKgNAQgFQARgGAWAAIAVAAIARADIAAgSQAAgNgIgGQgIgHgSAAQgPABgNADQgMAEgJAHIgPAAIAAglQANgGASgFQARgFAYAAQAnAAAUAOQAUAOAAAhIAACBIgWAAQgNAAgGgEQgGgDgDgMQgKAMgOAEQgMAFgQAAIgDAAgArmAWQgKAHAAANQAAAOAIAGQAIAHAOAAQAJAAAJgEQAIgEAGgGIAAgkQgMgDgPAAQgQABgJAFgAISBkIAAi7IAhAAQAJAAAEADQAEACACAIQABAHAAAOIAACZgAhrBkIAAi7IAjAAQAHAAAEAEQAEAFABANQAJgJANgHQANgIASAAIAEABIAFABIAAApIgHAAQgTABgOADQgNADgIAEIAACHgAngBkIAAh7QAAgOgGgFQgFgGgNAAQgMAAgLADIgTAGIAACLIg1AAIAAi7IAkAAQAGAAAEAEQAEAEACAMQAOgKARgHQASgGAUAAQANAAAMAFQALAEAHAMQAHALAAAVIAACJgAuSBkIAAjTIhEAAIAAgnIDBAAIAAAnIhFAAIAADTgABZhlIAAgKIAMgnIA2AAIAAAPIgkAigAIZhuQgIgHgBgMQABgMAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAMQAAAMgIAHQgIAIgMAAQgMAAgIgIg");
	this.shape.setTransform(0,2.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98.3,-13.2,196.8,31.8);


(lib.mc_sieres = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A60A5").s().p("ARMA1QgHgFAAgOIAAgsIgKAAIAAgQIAKAAIAAgWIAXAAIAAAWIASAAIAAAQIgSAAIAAAqQAAAGAEACQACACAGAAIAGAAIAAAOIgGACIgIABQgNAAgHgGgALUA1QgHgFAAgOIAAgsIgKAAIAAgQIAKAAIAAgWIAYAAIAAAWIARAAIAAAQIgRAAIAAAqQAAAGADACQACACAGAAIAGAAIAAAOIgGACIgIABQgNAAgHgGgAG+A0QgNgHgGgNQgHgNAAgSQAAgQAHgNQAHgOANgGQAMgHARgBIAOABIAKADIAJAEIAAATIgJAAQgEgEgFgCQgGgCgJAAQgOAAgIAKQgIAKAAARQAAAVAHAKQAHAKAPgBQAKAAAHgDIAKgIIAIAAIAAATQgGAFgJADQgJADgMAAQgQAAgMgHgASDA3QgGgDgDgFQgEgGgBgIQABgJAEgGQAEgGAIgDQAHgDALAAIAJABIAIABIAAgIQgBgEgDgDQgDgDgJAAQgGAAgGACIgKAFIgGAAIAAgRIANgFQAIgCALAAQASAAAIAGQAJAHAAAOIAAA5IgKAAQgFAAgDgBQgDgCgBgFQgFAFgGACQgGACgIAAQgIAAgGgDgASRAWQgEADAAAGQAAAGADADQAEADAGAAQAEAAAEgCQAEgBADgDIAAgQIgNgBQgHAAgEACgAOSAvQgMgMAAgUQABgOAEgIQAGgJAKgGQAIgFAMAAQAUAAAJAKQAKALAAATIAAAEIgBADIg3AAQABAIADAFQACAFAFACQAGACAGAAQAHAAAFgCQAHgCADgDIAIAAIAAAPIgNAGQgIACgNAAQgUAAgLgLgAO/AGQgBgJgEgFQgDgEgIAAQgDAAgEABQgDACgDAEQgCAFgBAGIAgAAIAAAAgAIcA1QgKgFgFgJQgGgKAAgOQAAgOAGgIQAFgJAKgGQAKgFAMAAQAMAAAKAFQAKAGAGAJQAFAIABAOQgBAOgFAKQgGAJgKAFQgKAFgMAAQgMAAgKgFgAIkgDQgFAEAAAOQAAAOAFAGQAGAHAIAAQAJAAAFgHQAFgGABgOQgBgOgFgEQgFgHgJAAQgIAAgGAHgAiRA1QgJgFgFgKQgEgKAAgNQAAgOAEgHQAFgKAJgFQAJgGALAAQARAAAJAKQAKAKgBATIAAAEIAAACIg4AAQAAAPAHAGQAGAHANAAQAHAAAGgDQAGgCAEgDIAFAAIAAALQgEAEgIACQgIADgLAAQgNAAgJgFgAhqAHQAAgLgFgGQgFgGgJAAQgIAAgGAGQgGAGgBALIAoAAIAAAAgAjvA2QgIgFgEgJQgFgJABgPQgBgQAGgIQAFgKAIgFQAIgEAJAAQAIAAAGADQAFACAEAEIAAgkIAJAAQAGAAABACQACACgBAHIAABkIgKAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQgBgCAAgHQgFAFgHAEQgGADgJAAQgIAAgIgEgAjjgLQgFADgDAGQgDAFgBAMQAAAMADAHQADAGAEADQAEADAHAAQAGAAAFgDQAGgDAEgFIAAgpQgDgEgFgCQgFgCgGAAQgFAAgGADgAlmA1QgIgFgFgKQgFgKAAgNQAAgOAFgHQAFgKAJgFQAJgGALAAQAQAAAKAKQAJAKAAATIAAAEIAAACIg5AAQABAPAGAGQAHAHAMAAQAIAAAGgDQAFgCAFgDIAEAAIAAALQgEAEgHACQgIADgLAAQgNAAgKgFgAk+AHQgBgLgFgGQgFgGgIAAQgJAAgGAGQgFAGgCALIApAAIAAAAgAmfA1QgGgFAAgMIAAgyIgLAAIAAgLIALAAIAAgXIAQAAIAAAXIATAAIAAALIgTAAIAAAwQAAAHADACQAEADAFAAIAIAAIAAALIgFABIgIAAQgLAAgGgFgApLA1QgJgFgFgKQgFgKABgNQAAgOAEgHQAGgKAJgFQAIgGALAAQARAAAJAKQAKAKgBATIAAAEIAAACIg4AAQAAAPAGAGQAIAHAMAAQAHAAAGgDQAGgCAEgDIAFAAIAAALQgFAEgHACQgIADgLAAQgNAAgJgFgAokAHQAAgLgFgGQgFgGgJAAQgIAAgGAGQgFAGgCALIAoAAIAAAAgArvAvQgLgMAAgUQAAgOAFgHQAGgKAKgGQAIgFANAAQAJAAAHACIAKAFIAAANIgIAAQgCgDgFgCQgFgCgHAAQgLAAgGAIQgHAGAAAPQAAAPAGAIQAHAIALAAQAJgBAEgCQAGgDACgDIAGAAIAAAMQgEAEgGACQgHADgKAAQgTAAgLgLgAtZA4IgLgFIAAgNIAFAAQADADAFACQAFACAJAAQAIAAAFgDQAEgDAAgGQAAgFgEgDQgEgDgJgBQgNgCgIgFQgGgGAAgKQAAgMAIgGQAIgGAOAAQAJAAAGABIAKAFIAAAMIgGAAIgHgEQgFgCgHAAQgIAAgDADQgFADAAAFQAAADAFADQADACAKACQAKABAGADQAGADADAFQADAFAAAIQAAAMgIAHQgIAHgQAAQgLAAgGgCgAupA1QgJgFgFgKQgEgKAAgNQAAgOAFgHQAFgKAJgFQAIgGALAAQARAAAKAKQAJAKAAATIAAAEIAAACIg5AAQABAPAGAGQAHAHAMAAQAIAAAFgDQAHgCADgDIAGAAIAAALQgFAEgHACQgIADgMAAQgNAAgJgFgAuBAHQgBgLgEgGQgGgGgJAAQgHAAgGAGQgGAGgBALIAoAAIAAAAgAw3A1QgJgFgFgKQgEgKgBgNQAAgOAGgHQAFgKAIgFQAJgGALAAQARAAAJAKQAJAKAAATIAAAEIAAACIg5AAQABAPAHAGQAGAHANAAQAHAAAGgDQAGgCAEgDIAFAAIAAALQgFAEgHACQgHADgMAAQgNAAgJgFgAwPAHQgBgLgFgGQgFgGgJAAQgIAAgGAGQgFAGgCALIApAAIAAAAgAzaA4QgIgDgHgEIAAgPIAHAAQAEAFAGADQAHADALAAQALAAAGgFQAGgEAAgKQAAgGgEgEQgDgEgGgCIgNgEQgJgCgIgEQgGgDgEgGQgCgGAAgJQAAgPAJgIQAKgIARAAQAJAAAIACQAIACAEADIAAAOIgGAAQgDgDgHgCQgFgDgIAAQgLAAgFAFQgFAEAAAIQAAAGADADQACAEAFACIAMADQAMADAHAEQAIACADAGQAEAHAAAKQAAAQgKAJQgKAIgTAAQgMAAgIgCgATSA5IAAhvIAOAAIAGABQACABABADIABAIIAABigAQZA5IAAg4QgBgEgCgDQgCgCgGAAQgFAAgGABIgJADIAAA9IgXAAIAAhTIAQAAQABAAAAAAQABABABAAQAAAAABAAQAAABAAAAQACACABAFQAGgEAIgDQAJgDAIAAQAHAAAEACQAFACAEAFQADAFAAAKIAAA8gANiA5IAAg4QAAgEgDgDQgCgCgGAAQgFAAgFABIgJADIAAA9IgXAAIAAhTIAPAAQABAAABAAQABABAAAAQABAAAAAAQABABAAAAQACACABAFQAGgEAIgDQAIgDAJAAQAGAAAFACQAFACAEAFQACAFAAAKIAAA8gAMDA5IAAhTIAPAAIAFABQACACAAADQACADgBAHIAABDgAKgA5IAAg4QAAgEgCgDQgCgCgGAAQgFAAgFABIgJADIAAA9IgYAAIAAhTIAQAAQABAAAAAAQABABABAAQAAAAABAAQAAABAAAAQACACACAFQAGgEAHgDQAJgDAIAAQAGAAAFACQAGACADAFQADAFAAAKIAAA8gAFkA5IgJgdIgmAAIgJAdIgVAAIAAgGIAlhpIAaAAIAnBpIAAAGgAFVALIgNgoIgBAAIgOAoIAcAAgADdA5IglhpIAAgGIAXAAIAcBRIAAAAIAchRIAVAAIAAAGIglBpgABfA5IAAhvIAnAAQAUAAAKAHQAKAHAAAQQAAAKgGAGQgFAFgJACIAAABQALAAAGAGQAHAGAAAMQAAAQgLAJQgLAIgVAAgAB4AnIAOAAQAKAAAEgEQAFgEgBgIQAAgIgEgEQgEgEgKAAIgOAAgAB4gIIANAAQAJAAADgEQAEgDAAgIQAAgGgEgEQgDgDgJAAIgNAAgAgBA5IAAhvIAlAAQAVAAAKAHQAJAHABAQQgBAKgFAGQgGAFgIACIAAABQAKAAAHAGQAGAGAAAMQABAQgLAJQgMAIgVAAgAAXAnIAOAAQAJAAAFgEQAEgEgBgIQAAgIgDgEQgFgEgJAAIgOAAgAAXgIIANAAQAIAAAEgEQAEgDgBgIQABgGgEgEQgEgDgIAAIgNAAgAhJA5IAAhvIAJAAQAFAAACACQABACAAAHIAABkgAnNA5IAAg5QAAgHgEgDQgDgDgGAAQgHAAgGADIgLAFIAAA+IgRAAIAAhSIAKAAQABAAAAAAQABAAABAAQAAAAABABQAAAAAAABQACACABAGQAFgFAJgDQAIgEAKAAQAFAAAFACQAGACACAFQAEAFAAAKIAAA8gAp/A5IAAhSIAJAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABIABAIIAABGgAqlA5IAAhvIAJAAQAFAAABACQABACAAAHIAABkgAvvA5IAAhSIAKAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQABACAAAHQAFgFAFgDQAHgEAIAAIACAAIACABIAAANIgCAAIgBAAQgJAAgHADQgFADgFADIAAA8gAyOA5IAAhSIAKAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAIIAABGgAMFgkQgDgEAAgFQAAgFADgEQAEgDAFgBQAGABADADQAEAEABAFQgBAFgEAEQgDADgGABQgFgBgEgDgAp+gmQgCgCAAgEQAAgFACgCQADgDAEAAQAFAAADADQACACAAAFQAAAEgCACQgDADgFAAQgEAAgDgDgAyMgmQgDgCgBgEQABgFADgCQACgDAEAAQAFAAACADQADACAAAFQAAAEgDACQgCADgFAAQgEAAgCgDg");
	this.shape.setTransform(-0.2,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-126,-5.9,251.6,11.9);


(lib.mc_rainbow = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B8E5F8").s().p("AoQDUIAAmnIQgAAIAAGng");
	this.shape.setTransform(581.8,21.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#8ED1F2").s().p("AoPDUIAAmnIQfAAIAAGng");
	this.shape_1.setTransform(476,21.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#5DBEEC").s().p("AoPDUIAAmnIQfAAIAAGng");
	this.shape_2.setTransform(370.2,21.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#399FD8").s().p("AoPDUIAAmnIQfAAIAAGng");
	this.shape_3.setTransform(264.4,21.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#3374B9").s().p("AoQDUIAAmnIQhAAIAAGng");
	this.shape_4.setTransform(158.7,21.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2C5AA3").s().p("AoPDUIAAmnIQfAAIAAGng");
	this.shape_5.setTransform(52.9,21.3);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,634.7,42.6);


(lib.mc_prestamo = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A60A5").s().p("ANoCFIAAhEQgIAHgLAFQgMAEgOAAQgSAAgPgIQgQgIgJgSQgJgRAAgbQAAgdAKgTQALgTAQgIQAQgJASAAQAQABALAEQALAEAIAIQADgGAEgEQAFgEAGAAIAWAAIAADTgAM5gqQgIAEgGALQgFAKAAARQAAASADALQAEALAHAFQAIAEAMAAQAJAAAIgDQAIgDAHgFIAAhLQgGgEgHgDQgGgCgKAAIgCAAQgJAAgHAEgAqGBLQgNgLAAgZIAAhXIgUAAIAAgeIAUAAIAAgrIAtAAIAAArIAhAAIAAAeIghAAIAABSQAAALAFAFQAFAEALAAIAMAAIAAAbIgMADQgHABgJAAIgCAAQgWAAgNgKgAR8A/QgVgWAAgnQAAgYAKgTQALgTARgKQASgKAXgBQAkAAATAUQASAUAAApIAAAGIAAAFIhqAAQABARAGAJQAFAJAJAEQAKADAMAAQAOAAALgEQAKgEAIgGIAOAAIAAAeQgJAGgQAFQgPAFgYAAQgoAAgVgWgATTgOQgBgVgHgJQgIgIgNAAQgIAAgGADQgHADgFAJQgEAIgCAPIA9AAIAAAAgAPPBRQgKgEgHgKQgGgJAAgRIAAh3IAuAAIAABsQAAAMAGAFQAGAFALgBQAIAAAJgCIARgGIAAh5IAtAAIAAChIgfAAQgFAAgEgDQgDgDgCgJQgLAIgPAEQgOAFgPAAQgOAAgLgEgAJqBLQgTgKgLgSQgLgTAAgaQAAgYALgTQALgTATgKQATgKAXgBQAXABATAKQATAKALATQALATAAAYQAAAagLATQgLASgTAKQgTAKgXAAQgXAAgTgKgAJ5gjQgKANAAAZQAAAaAKAMQAKAMARAAQARAAAKgMQAKgMAAgaQAAgZgKgNQgKgNgRAAQgRAAgKANgAhSBLQgTgKgLgSQgLgTAAgaQAAgYALgTQALgTATgKQATgKAXgBQAXABARAKQATAKALATQALATAAAYQAAAagLATQgLASgTAKQgRAKgXAAQgXAAgTgKgAhDgjQgKANAAAZQAAAaAKAMQAKAMARAAQARAAAKgMQAKgMAAgaQAAgZgKgNQgKgNgRAAQgRAAgKANgAvFA/QgVgWAAgnQAAgYAKgTQALgTARgKQASgKAXgBQAkAAATAUQASAUAAApIAAAGIAAAFIhqAAQABARAGAJQAFAJAJAEQAKADAMAAQAOAAALgEQAKgEAIgGIAOAAIAAAeQgJAGgQAFQgPAFgYAAQgoAAgVgWgAtugOQgBgVgHgJQgIgIgNAAQgIAAgGADQgHADgFAJQgEAIgCAPIA9AAIAAAAgACOBPQgMgFgHgLQgHgLAAgQQAAgRAJgMQAIgJAPgGQAOgFATAAIASABIAPADIAAgQQAAgLgHgGQgHgGgQAAQgNAAgLAEQgKADgIAGIgNAAIAAggQALgFAPgEQAPgEAVgBQAiAAARANQARAMAAAcIAABvIgTAAQgLAAgFgDQgGgEgCgJQgJAJgLAEQgMAFgPAAQgPAAgMgGgACoAQQgIAFAAAMQAAAMAHAGQAHAFAMAAQAIAAAHgEQAHgDAGgFIAAgfQgLgCgNAAQgNAAgJAFgAodBPQgLgFgHgLQgHgLAAgQQAAgRAIgMQAJgJAOgGQAPgFATAAIARABIAPADIAAgQQAAgLgHgGQgHgGgQAAQgMAAgLAEQgLADgIAGIgNAAIAAggQAMgFAPgEQAPgEAVgBQAhAAARANQARAMAAAcIAABvIgTAAQgKAAgGgDQgFgEgCgJQgJAJgMAEQgMAFgPAAQgPAAgMgGgAoCAQQgIAFAAAMQAAAMAHAGQAHAFALAAQAJAAAHgEQAHgDAFgFIAAgfQgLgCgMAAQgOAAgIAFgAsYBRQgOgEgJgGIAAghIAOAAQAGAFAKAEQAKAEAOAAQAOAAAHgDQAHgEAAgIQAAgHgGgEQgGgEgRgCQgbgDgNgMQgOgJAAgYQAAgYARgNQARgOAeAAQASAAAMADQAMADAJAFIAAAhIgNAAQgGgEgJgDQgKgDgMgBQgOAAgFAEQgGAEAAAHQAAAGAHAEQAHADAQACQAUADAMAFQAMAGAGAIQAFALAAAQQABAYgRAOQgQAOgkABQgTgBgOgDgAHiBTIAAi1Ig8AAIAAgiICnAAIAAAiIg7AAIAAC1gAElBTIAAjXIAcAAQAHAAAEACQAEABABAGIABAQIAAC+gAjABTIAAhqQAAgMgFgFQgEgEgKAAQgKAAgJACIgQAGIAAB3IgtAAIAAhqQAAgMgFgFQgEgEgKAAQgKAAgJACIgQAFIAAB4IgtAAIAAihIAfAAQAFAAAEAEQADADABAKQALgIAPgGQAPgFAQgBQANAAALAFQAKAFAFALQANgJAPgGQAQgFAQgBQAMAAAKAFQAJAEAGAKQAGAKAAARIAAB2gAxHBTIAAihIAfAAQAFAAAEAEQADAEACAMQAHgJALgGQAMgGAPAAIAFAAIAFABIAAAkIgIAAQgRAAgMADQgLADgHADIAAB0gAz+BTIAAjXIBIAAQApAAAXAQQAWARAAAkQAAAjgXARQgWAPgqAAIgXAAIAABPgAzOgaIAXAAQAVAAAJgKQAJgJgBgSQABgLgEgIQgDgIgJgEQgIgEgPAAIgXAAgAuYhZIAAgKIALghIAuAAIAAANIgfAeg");
	this.shape.setTransform(0.5,2.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-127.4,-10.7,256,26.8);


(lib.mc_pc = function() {
	this.initialize();

	// Capa 1
	this.instance = new lib.img_pcmin();
	this.instance.setTransform(-167.9,-139.9);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-167.9,-139.9,970,250);


(lib.mc_pantalla = function() {
	this.initialize();

	// Capa 1
	this.instance = new lib.img_pantallamin();
	this.instance.setTransform(-54.9,-20.9);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-54.9,-20.9,110,42);


(lib.mc_logo = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#075095").s().p("AhFFHIjXqNIB0AAQAhAAAOAPQAPAPASA3IB6GaICUnvIBnAAIjIKNg");
	this.shape.setTransform(19.2,5,0.148,0.148);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#075095").s().p("Aj5FHIAAqNIEbAAQBiAAAiBDQAhBCg0BMIggAwQBQAqAiBDQAgBAgRBDQgQBDg4ArQg9AuhXAAgAhfDwIAvAAQA8AAAkgiQAngkAAhHQAAg7gagkQgZgfgrgLIA1hRQARgYAAgYQAAgegXgWQgWgWgdAAIhUAAg");
	this.shape_1.setTransform(3.7,5,0.148,0.148);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#075095").s().p("Aj5FHIAAqNIEcAAQBiAAAhBDQAhBCg0BMIggAwQBRAqAiBDQAfBAgQBDQgQBDg5ArQg8AuhXAAgAheDwIAuAAQA8AAAkgiQAngkAAhHQAAg7gagkQgYgfgrgLIA1hRQAQgZAAgXQAAgegWgWQgXgWgcAAIhUAAg");
	this.shape_2.setTransform(11.9,5,0.148,0.148);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#075095").s().p("AB8FHIgriNIjsAAIgrCNIhmAAIDIqNIB7AAQAmAAAOANQAOAMAOAqIDGJKgAA0BaIhZkpIhaEpICzAAg");
	this.shape_3.setTransform(26.8,5,0.148,0.148);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#075095").s().p("Ah1DTQg3gmgXhGQgPgtAAg4QAAhTAkg+QAig8A9gcQApgSAtAAQA0AAAoARQAqASAbAkQASAZAKAgQAPArAAA7IAAAgIlhAAQACAuAMAiQANAmAaAXQASAQAXAIQAfAMApAAQAaAAAdgGQAbgGARgHQAngTAGAAQAVgCAUAgQgdAfg1AUQgxARg7AAQhQAAg4gngACPgqQgCgpgLgfQgNgfgVgUQgOgLgTgIQgZgIgfAAQgrAAgjAXQgiAXgTAsQgLAdgFAfIEbAAIAAAAg");
	this.shape_4.setTransform(75.7,6.1,0.148,0.148);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#075095").s().p("AinD7QhbhaAAigIAAgBQAAigBbhaQBQhPB0AAQAaAAASACQAXACAXAFIABAAQAeAJARAIQAlASAdAdQAOAPAMARQgTAVgPAEQgNADgOgIIgPgLIgUgRIgFgDIAAgBIgSgKQgdgOgmgFQgVgDgUAAQhkAAg7BIQg7BHAAB7IAAAFQAAB7A7BIQA7BHBkAAQAUAAAVgDQAmgFAdgOIASgKIAAgBIAZgUQAGgFAJgFQAOgJANADQAPAEATAVQgLAQgPAQQgdAdglASQgRAIgeAJIgBAAQgVAGgZACQgUABgYAAQh0AAhQhPg");
	this.shape_5.setTransform(37.9,4.9,0.148,0.148);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#075095").s().p("Ah1DmQgpgWgTgqQgLgcAAgjQAAgqASggQASgdAjgSQAXgLAagHQAmgJAnAAQA+AAAzAMIAAhGQgBgcgIgSQgKgRgQgKQgLgHgOgDQgigHgNAAQgzAAglAQQgiAOgNgBQgXgDgRgjQAkgVAggLQAzgQA8AAQAqAAAiAKQAjAJAWAWQAPAPALAVQAMAdgBAmIAAFgIgYAAQgKAAgGgBQgIgCgHgGIgHgIQgCgEgCgLIgBgQQgXAUgbANQgrAUg2AAQg1AAgngVgAgvAQQgcAGgQAPQgNAKgGAMQgKARAAAYQAAAcAKATQAJATAQAKQAKAGAOAFQASAGAYgBQAwAAAjgTQAdgQAdghIAAhmQg4gNg2AAQgjAAgYAHg");
	this.shape_6.setTransform(94.5,6.1,0.148,0.148);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#075095").s().p("AghFHIAAqNIAcAAQAZAAAHANQAHAKAAAgIAAJWg");
	this.shape_7.setTransform(99.4,5,0.148,0.148);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#075095").s().p("AhFDEIAAlAIg+AAIAAg5IA+AAIAAiDIBEAAIAACDIB8AAIAAA5Ih8AAIAAE7QAAAkANANQAPAOAoAAIBBAAIAAA0IgJACQgbAFgsAAQh5AAAAh1g");
	this.shape_8.setTransform(89,5.2,0.148,0.148);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#075095").s().p("ACCD5IAAljQAAgrgUgTQgTgTgsAAQhOAAhiBKIAAFqIhEAAIAAnsIAgAAQAXABAIAPQAFAMAAAfIAAAFQBfhEBiAAQBCgBAiAjQAiAjAABDIAAFog");
	this.shape_9.setTransform(83.1,6.1,0.148,0.148);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#075095").s().p("ACCD5IAAljQAAgrgTgTQgTgTgsAAQhOAAhjBKIAAFqIhEAAIAAnsIAhAAQAXABAHAPQAFAMAAAfIAAAFQBghEBiAAQBBgBAiAjQAiAjAABDIAAFog");
	this.shape_10.setTransform(68.5,6.1,0.148,0.148);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#075095").s().p("AggD2IAAnrIAaAAQAYAAAJAOQAGAMAAAiIAAGvg");
	this.shape_11.setTransform(63.4,6.1,0.148,0.148);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#075095").s().p("AgdAeQgMgNABgRQAAgQAMgMQAMgNAQAAQAQAAANANQAMAMAAAQQABARgMANQgNAMgRAAQgQAAgNgMg");
	this.shape_12.setTransform(63.4,1.1,0.148,0.148);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#075095").s().p("AhFDEIAAlAIg+AAIAAg5IA+AAIAAiDIBEAAIAACDIB7AAIAAA5Ih7AAIAAE7QAAAkANANQAPAOAoAAIBBAAIAAA0IgJACQgbAFgtAAQh4AAAAh1g");
	this.shape_13.setTransform(59.4,5.2,0.148,0.148);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#075095").s().p("ACCD5IAAljQgBgrgSgTQgUgTgrAAQhPAAhhBKIAAFqIhFAAIAAnsIAgAAQAXABAIAPQAFAMABAfIAAAFQBehEBjAAQBBgBAiAjQAhAjAABDIAAFog");
	this.shape_14.setTransform(53.5,6.1,0.148,0.148);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#075095").s().p("AimC2Qg/hEAAhyQAAhxA/hEQA/hFBnAAQBoAAA/BFQA/BEAABxQAAByg/BEQg/BEhoABQhngBg/hEgAh1iMQgrA0AABYQAABaArA0QArAzBKAAQBLAAArgzQArg0AAhaQAAhYgrg0QgrgzhLAAQhKAAgrAzg");
	this.shape_15.setTransform(45.8,6.1,0.148,0.148);

	this.addChild(this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,100,9.8);


(lib.mc_ingresa = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A60A5").s().p("ACTBaIAAiOIAVAAQADAAADACQACACABAHQAGgGAJgDQAIgEALAAQALAAAJAGQAKAEAGANQAHALAAAUQAAATgIAMQgGANgMAGQgLAFgMAAQgJAAgGgDQgHgCgGgDIAAArgAC8gdIgLAEIAAA1QAFACAEACQAFACAHgBQAGABAGgDQAFgCAEgIQADgHAAgNQAAgMgDgHQgDgHgGgDQgFgDgGABIgLABgAxIBVQgJgCgHgEIAAgOIAHAAQAEADAIADQAIADAJAAQANgBAIgFQAIgFAAgMIAAgLQgGAGgHAEQgIADgJAAQgLABgIgFQgKgFgFgLQgGgKAAgRQAAgQAHgLQAFgMALgFQAJgFAKAAQAKAAAHADQAHADAFAFQABgEACgDQACgCAEAAIAJAAIAABdQAAAMgFAIQgGAIgKAEQgLAEgOAAQgNAAgJgDgAw7gYQgGADgEAHQgEAIAAALQAAANADAHQADAIAGAEQAGADAGAAQAIgBAHgEQAGgDAFgFIAAguQgFgEgFgCQgFgCgIgBQgGAAgHAEgATFAyQgIgGgBgSIAAg5IgMAAIAAgVIAMAAIAAgeIAgAAIAAAeIAVAAIAAAVIgVAAIAAA2QAAAHACADQAEADAHABIAJAAIAAASIgIACIgMABIgBAAQgPAAgJgIgALKAyQgIgGgBgSIAAg5IgNAAIAAgVIANAAIAAgeIAfAAIAAAeIAWAAIAAAVIgWAAIAAA2QAAAHADADQAEADAHABIAIAAIAAASIgIACIgLABIgCAAQgPAAgIgIgAROAqQgOgOAAgaQAAgRAHgNQAHgMAMgHQAMgHAQAAQAYAAANAOQAMANAAAbIAAAEIAAADIhIAAQABALAEAHQADAGAHACQAGADAIAAQAKAAAHgDQAHgDAGgEIAJAAIAAAVQgGAEgKADQgLADgQABQgcgBgOgPgARsggQgFABgDAHQgDAFgBAKIApAAQgBgOgFgGQgFgGgIAAIgCAAQgEAAgEADgAMPAqQgPgOAAgaQAAgRAIgNQAGgMANgHQALgHAQAAQAYAAANAOQANANAAAbIAAAEIAAADIhIAAQABALADAHQAEAGAGACQAHADAIAAQAJAAAIgDQAHgDAFgEIAJAAIAAAVQgGAEgKADQgKADgRABQgbgBgOgPgAMsggQgEABgEAHQgCAFgBAKIAoAAQAAgOgFgGQgFgGgJAAIgCAAQgEAAgEADgAElAzQgNgHgIgNQgHgMAAgRQAAgRAHgNQAIgMANgHQANgHAPAAQAQAAANAHQANAHAHAMQAIANAAARQAAARgIAMQgHANgNAHQgNAGgQABQgPgBgNgGgAFTAcQAHgJAAgRQAAgRgHgIQgGgJgMAAQgLAAgHAJQgHAIAAARQAAARAHAJQAHAIALgBQAMABAGgIgAhlAqQgPgOAAgbQAAgPAHgOQAJgMANgHQANgHAQAAQAOAAAHADQAJACAFACIAAAYIgMAAQgEgEgFgCQgGgDgIABQgMgBgHAKQgIAIAAAQQAAARAIAJQAGAHAMAAQALAAAFgDQAGgCAEgEIAKAAIAAAWQgFADgJADQgJADgNABQgbgBgPgPgAAXA5QgJAAgJgEQgFgDgFgIQgFgHAAgLQAAgMAFgHQAFgGAJgDQAKgFANAAIAMABIAKACIAAgLQAAgHgFgEQgEgEgLABQgJAAgHABQgHADgGAEIgHAAIAAgWQAHgEAJgCQALgDANAAQAXAAAMAIQALAIAAATIAABLIgMAAQgIAAgDgCQgEgDgBgGQgHAGgIAEQgGACgJAAIgDAAgAAXALQgFADAAAIQAAAJAEADQAFAEAIAAQAGAAAFgDIAIgFIAAgWIgQgBIgCAAQgIAAgFAEgAk8A5QgKAAgIgEQgIgDgFgIQgFgHAAgLQAAgMAGgHQAGgGAKgDQAKgFAMAAIAMABIALACIAAgLQgBgHgEgEQgFgEgKABQgKAAgGABQgIADgGAEIgIAAIAAgWQAIgEAKgCQAKgDAOAAQAXAAAMAIQALAIAAATIAABLIgNAAQgHAAgDgCQgEgDgCgGQgGAGgIAEQgHACgIAAIgDAAgAk8ALQgGADABAIQgBAJAFADQAEAEAJAAQAFAAAFgDIAJgFIAAgWIgRgBIgCAAQgIAAgEAEgApaA2QgHgEgEgGQgEgHAAgJQAAgLAEgGQAFgHAJgDQAJgCALAAIAMABIAKAAIAAgLQAAgJgFgEQgFgEgKAAQgJAAgGACQgIACgEAEIgGAAIAAgPIAPgFQAJgDAMAAQASAAAJAHQAKAHAAARIAABEIgIAAQgFAAgDgCQgDgDAAgGQgGAGgHADQgHADgKAAQgJAAgHgDgApQANQgGAFgBAIQABAKAFAEQAFAEAIAAQAIAAAGgEQAFgDAEgFIAAgUIgIgCIgKAAQgKAAgHADgArmA2QgGgEgEgGQgEgHgBgJQABgLAEgGQAFgHAKgDQAIgCAMAAIALABIAKAAIAAgLQAAgJgFgEQgFgEgKAAQgJAAgHACQgGACgFAEIgGAAIAAgPIAPgFQAIgDAMAAQATAAAJAHQAJAHAAARIAABEIgHAAQgFAAgDgCQgDgDgBgGQgFAGgHADQgHADgKAAQgJAAgIgDgArbANQgGAFAAAIQAAAKAFAEQAFAEAIAAQAIAAAFgEQAGgDAEgFIAAgUIgJgCIgKAAQgKAAgGADgAs6A2QgIgCgGgEIAAgPIAHAAQAEAEAFADQAHACAKAAQAKAAAFgDQAFgEAAgHQAAgHgEgDQgFgDgMgCQgPgCgIgGQgIgFgBgNQABgPAJgHQAKgIAQABQALAAAHACQAHABAEADIAAAPIgFAAQgEgCgFgDQgHgCgIAAQgJAAgEAEQgFADAAAGQAAAGAFADQAEADAMABQALACAHACQAHACAEAHQADAFAAAKQAAAOgJAJQgJAHgUABQgMgBgHgCgAuYAzQgKgGgFgMQgGgLAAgQQAAgNAGgMQAGgLAKgHQALgGAMAAQAUAAALAMQALAMAAAWIAAAEIAAADIhDAAQABARAHAIQAIAHAOAAQAKABAGgDIAMgHIAGAAIAAAOIgOAHQgJADgOAAQgPAAgLgGgAtpgBQgBgQgFgGQgGgHgLAAQgKAAgGAHQgHAHgCAPIAwAAIAAAAgAQRA4IAAhHQAAgIgEgEQgDgDgHAAQgHABgHABIgLAEIAABQIgeAAIAAhsIAUAAQAFAAACACQACACABAIQAHgHALgDQAKgEAMAAQAIAAAGADQAIACADAHQAFAHAAAMIAABPgAN4A4IAAhsIAWAAQADAAACADQADACABAIQAFgFAHgFQAIgEAKgBIAEABIADABIAAAYIgFAAQgLAAgJACQgHACgFADIAABNgAKIA4IAAhHQAAgIgEgEQgDgDgIAAQgGABgHABIgMAEIAABQIgeAAIAAhsIAVAAQAEAAACACQADACAAAIQAIgHAKgDQALgEAMAAQAHAAAHADQAHACAEAHQAEAHAAAMIAABPgAIHA4IAAiRIAhAAIAACRgAGLA4IAAhsIAVAAQADAAADADQACACABAIQAFgFAHgFQAIgEAKgBIAEABIADABIAAAYIgFAAQgLAAgJACQgHACgFADIAABNgAijA4IAAhHQAAgIgEgEQgDgDgHAAQgHABgHABIgLAEIAABQIgeAAIAAhsIAUAAQAFAAACACQACACABAIQAHgHALgDQAKgEAMAAQAIAAAGADQAIACADAHQAFAHAAAMIAABPgAnYA4IAAiRIAzAAQAaAAANAJQANAJAAAVQgBANgGAHQgIAHgLADIAAABQAOADAIAHQAJAJAAANQAAAVgOALQgOALgbAAgAm3AhIATAAQAMAAAFgGQAGgFgBgKQABgLgGgDQgFgGgMAAIgTAAgAm3geIARAAQALAAAEgEQAGgEAAgKQAAgJgGgFQgEgEgLAAIgRAAgAvrA4IAAhhIANAAQADAAACACQACADAAAIQAFgFAHgFQAIgEAIAAIAEAAIACABIAAAPIgCAAIgCAAQgKABgIADQgHADgFAFIAABGgAyDA4IAAhDQAAgJgDgDQgFgEgHAAQgIAAgHAEIgOAGIAABJIgUAAIAAhhIANAAQADAAACACQACADAAAHQAHgGAKgEQAKgEALAAQAHAAAGADQAGABADAHQAEAFgBAMIAABHgAzwA4IAAhhIALAAIAGABQAAAAABAAQAAABAAAAQABABAAABQAAAAAAABIABAJIAABTgAzug4QgDgDAAgFQAAgEADgEQAEgDAEAAQAFAAADADQADAEAAAEQAAAFgDADQgDADgFAAQgEAAgEgDg");
	this.shape.setTransform(2.4,1.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-124.2,-7.2,253.3,18.1);


(lib.mc_fondo = function() {
	this.initialize();

	// Capa 1
	this.instance = new lib.img_fondocremamin();
	this.instance.setTransform(-167.9,-139.9);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-167.9,-139.9,970,250);


(lib.mc_espedir = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1A60A5").s().p("AqzB0IAAi3IASAAQAFAAACADQACAEABALQAIgIALgGQAMgGAPAAQANAAAMAGQAMAHAIAPQAIAQAAAZQAAAZgJARQgJAQgNAHQgOAHgOgBQgOAAgKgDQgJgDgHgGIAAA5gAqHgqQgIAFgIAGIAABGQAGAGAIADQAIADAKAAQALAAAIgEQAJgEAFgLQAGgLAAgUQAAgSgFgLQgFgLgIgEQgIgEgJAAQgKAAgKAFgAONBCQgQgJgKgQQgJgQgBgXQABgVAJgQQAKgRAQgJQARgJAUAAQAUAAAQAJQARAJAJARQAKAQAAAVQAAAXgKAQQgJAQgRAJQgQAIgUAAQgUAAgRgIgAObgeQgKALABAVQgBAXAKALQAIAKAPAAQAOAAAKgKQAIgLAAgXQAAgVgIgLQgKgMgOAAQgPAAgIAMgAJbA3QgSgTAAgiQAAgVAJgQQAJgRAPgJQAQgJAUAAQAgAAAPASQAQARABAjIgBAFIAAAFIhbAAQABAOAEAIQAFAIAIADQAIAEALgBQAMAAAJgDQAJgDAHgFIAMAAIAAAaQgIAFgNAEQgNAEgVAAQgjAAgTgTgAKngMQAAgSgHgIQgGgHgMAAQgHAAgFADQgGADgFAHQgEAHgBANIA1AAIAAAAgAHFBHQgJgEgGgIQgEgJgBgOIAAhnIAoAAIAABdQgBALAGAEQAFAEAKAAQAHAAAIgCIAOgFIAAhpIAoAAIAACLIgbAAQgFABgDgDQgDgDgBgIQgKAHgMAEQgNAEgOAAQgLAAgKgDgABbBHQgJgEgFgIQgFgIAAgPIAAhnIAbAAIAABhQABAOAGAEQAFAFALAAQALgBAJgEQALgEAIgFIAAhqIAcAAIAACLIgSAAQgEABgCgEQgDgDgBgKQgKAIgNAFQgNAFgOAAQgLAAgJgDgAgBBCQgKgJAAgUIAAhVIgRAAIAAgTIARAAIAAgmIAaAAIAAAmIAfAAIAAATIgfAAIAABSQAAALAEAEQAFAFALgBIANAAIAAASIgKACIgNABQgSAAgIgIgAl3BDQgNgIgHgPQgHgQgBgYQABgaAIgQQAJgRANgHQANgHAPAAQAOAAAKAEQAJAEAHAGIAAg8IAPAAQAIAAACADQADAEgBAMIAACoIgSAAQgEABgCgEQgCgEgBgMQgHAJgLAGQgMAGgOAAQgPAAgMgHgAligrQgKAEgFAMQgGALAAASQABATAEAMQAEALAHAFQAIAFAKAAQAMgBAIgEQAJgFAIgJIAAhGQgGgGgHgDQgJgDgKAAQgKAAgIAEgAoCBBQgPgJgJgQQgHgQgBgWQABgVAIgQQAIgQAPgJQAPgJASAAQAcAAAQARQAPAQAAAjIAAAEIAAAEIhfAAQABAZALAKQALALAUAAQAOAAAJgEQAKgEAGgFIAJAAIAAATQgHAGgNAEQgMAFgUAAQgVAAgPgJgAnBgJQAAgXgJgJQgIgKgPABQgOgBgKAKQgJAKgCAWIBDAAIAAAAgAtaBGQgLgEgHgFIAAgVIAJAAQAFAFAIAEQAKADANAAQAOAAAIgFQAHgFAAgKQAAgJgGgEQgHgFgQgDQgWgCgMgJQgLgIAAgTQAAgUANgLQAOgKAXgBQAPABAKADQAKACAHAEIAAAWIgJAAQgFgFgIgDQgIgCgLAAQgOAAgGAEQgHAFAAAJQAAAIAHAEQAHAFAQACQAQACAKAFQAKADAFAIQAFAIAAAOQAAAUgNAMQgOALgbABQgSgBgKgDgAMLBIIg0iBIAAgKIAlAAIAkBfIABAAIAhhfIAhAAIAAAKIgyCBgAFsBIIAAhcQAAgKgFgEQgEgEgIAAIgSACIgPAEIAABoIgnAAIAAiLIAbAAQAEgBAEAEQADADABAJQAKgIAOgFQANgFAOAAQALAAAIAEQAJADAFAJQAFAIAAAQIAABmgAivBIIAAiLIASAAQAFAAACAEQACADABAMQAGgIALgGQAKgGANAAIAFAAIACABIAAAWIgCAAIgEAAQgOAAgKAFQgLAFgGAGIAABlgAjwBIIAAiLIAQAAQAFAAACACQADABABAFIABANIAAB2gAv5BIIAAi7IB0AAIAAAXIhXAAIAAA7IA/AAIAAAVIg/AAIAAA+IBZAAIAAAWgAjthYQgEgEgBgHQABgGAEgFQAFgFAGAAQAHAAAFAFQAEAFABAGQgBAHgEAEQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(0.7,2.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-101.1,-9.3,203.7,23.3);


(lib.mc_comoesto = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFDBRQgMgJAAgWIAAhLIgRAAIAAgaIARAAIAAgmIAnAAIAAAmIAdAAIAAAaIgdAAIAABHQAAAKAFADQAEAEAKAAIALAAIAAAYIgLACIgOABIgCAAQgTAAgLgJgAGsBSQgQgJgKgQQgJgQgBgXQABgVAJgQQAKgRAQgJQAQgJAVAAQAUAAAQAJQAQAJAKARQAKAQAAAVQAAAXgKAQQgKAQgQAJQgQAIgUAAQgVAAgQgIgAG5gOQgJALAAAVQAAAXAJALQAJAKAPAAQAOAAAJgKQAJgLAAgXQAAgVgJgLQgJgMgOAAQgPAAgJAMgAAtBHQgTgTAAgiQAAgVAJgQQAJgRAQgJQAPgJAUAAQAgAAAQASQAQARAAAhIAAAHIAAAFIhcAAQABAOAEAIQAFAIAIADQAIAEALgBQAMAAAJgDQAKgDAHgFIAMAAIAAAaQgJAFgNAEQgNAEgVAAQgjAAgSgTgAB4ACQAAgQgHgIQgGgHgMAAQgHAAgFADQgGADgEAHQgEAHgCALIA1AAIAAAAgAiSBSQgRgJgJgQQgKgQAAgXQAAgVAKgQQAJgRARgJQAQgJAUAAQAUAAARAJQAQAJAKARQAJAQAAAVQAAAXgJAQQgKAQgQAJQgRAIgUAAQgUAAgQgIgAiFgOQgJALAAAVQAAAXAJALQAIAKAPAAQAPAAAJgKQAIgLABgXQgBgVgIgLQgJgMgPAAQgPAAgIAMgAoiBSQgQgJgKgQQgJgQgBgXQABgVAJgQQAKgRAQgJQAQgJAVAAQAUAAAQAJQAQAJAKARQAKAQAAAVQAAAXgKAQQgKAQgQAJQgQAIgUAAQgVAAgQgIgAoVgOQgJALAAAVQAAAXAJALQAJAKAPAAQAOAAAJgKQAJgLAAgXQAAgVgJgLQgJgMgOAAQgPAAgJAMgAq3BHQgTgTgBgiQABgVAJgRQAKgQARgJQARgJAWAAQAQAAAKADQALADAGAEIAAAdIgPAAQgEgEgIgDQgHgDgJAAQgQAAgKALQgKAMAAAUQAAAXAKAKQAJALAPAAQANgBAHgDQAIgDAEgFIAOAAIAAAbQgHAFgLAEQgMAEgQAAQgjAAgTgTgAKmBUQgGgGgBgKQABgJAGgGQAGgGAKgBQAJABAGAGQAGAGABAJQgBAKgGAGQgGAGgJAAQgKAAgGgGgAJoBUQgGgGAAgKQAAgJAGgGQAHgGAJgBQAJABAHAGQAGAGAAAJQAAAKgGAGQgHAGgJAAQgJAAgHgGgAIrBUQgGgGgBgKQABgJAGgGQAGgGAJgBQAKABAGAGQAGAGABAJQgBAKgGAGQgGAGgKAAQgJAAgGgGgADDBWQgMgDgIgFIAAgdIANAAQAFAFAIADQAJAEAMAAQAMAAAHgDQAGgEAAgGQAAgHgFgDQgGgEgOgBQgYgDgMgKQgMgKAAgSQABgWAOgLQAPgMAaAAQAQAAAKADQALACAIAFIAAAcIgMAAQgFgEgIgCQgIgDgLAAQgMAAgFADQgFADAAAGQAAAGAGADQAGADAPAAQARACAKAFQALAFAFAJQAFAJAAAOQAAAVgPAMQgOANgfAAQgRAAgMgEgAjzBYIAAhcQAAgKgDgEQgEgEgJAAQgJAAgHACIgOAFIAABnIgoAAIAAhcQAAgKgEgEQgDgEgJAAQgJAAgHACIgOAEIAABoIgoAAIAAiLIAbAAQAFgBADAEQADADABAIQAJgHANgFQANgFAPAAQALAAAJAEQAJAEAEAKQALgIAOgFQAOgFAOAAQAKAAAIAEQAJADAFAJQAFAJAAAPIAABmg");
	this.shape.setTransform(0,0.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71.6,-8.3,143.3,18.2);


(lib.mc_boton = function() {
	this.initialize();

	// Capa 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgBBrIAAg2QgHAFgJAEQgKADgLAAQgPAAgMgGQgMgHgHgOQgIgOAAgVQAAgYAJgPQAHgPANgHQANgHAPAAQANABAJADQAJAEAEAGQACgFAEgDQAEgDAFAAIASAAIAACpgAgnghQgHADgFAIQgEAJAAANQAAAPADAIQACAJAHAEQAGAEAKAAQAGAAAIgDQAGgCAGgFIAAg7QgFgEgFgCQgGgCgIAAQgIAAgGAEgABQBBQgJgDgEgIQgGgIAAgNIAAhfIAlAAIAABWQAAAKAFAEQAFAEAIgBQAHAAAIgCIANgEIAAhhIAkAAIAACBIgYAAQgEAAgDgDQgDgCgBgHQgKAGgMAEQgLADgNABQgKAAgJgEgADSBDIAAiBIAWAAQAHgBACACQADACACAFIABAQIAABpgAiLBDIgPgtIg7AAIgOAtIggAAIAAgLIA7iiIAoAAIA6CiIAAALgAijgDIgVhAIAAAAIgVBAIAqAAgADWhIIAAgIIAJgaIAkAAIAAAKIgYAYg");
	this.shape.setTransform(0.2,1.1);

	// Capa 1
	this.instance = new lib.img_botonmin();
	this.instance.setTransform(-67.4,-21.9);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-67.4,-21.9,135,44);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;

function reloadAd() {
    function A() {
        setTimeout(function() {
            g.style.display = "block"
        }, 16000)
    }
    var g = document.getElementById("reload");
    A(), g.onclick = function() {
        g.style.display = "none", A()
    }
}